/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HerbariumRouteImport } from './routes/herbarium'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecimenIdRouteImport } from './routes/specimen.$id'
import { Route as SpeciesIdRouteImport } from './routes/species.$id'
import { Route as ApiRemoveBackgroundRouteImport } from './routes/api/remove-background'

const HerbariumRoute = HerbariumRouteImport.update({
  id: '/herbarium',
  path: '/herbarium',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecimenIdRoute = SpecimenIdRouteImport.update({
  id: '/specimen/$id',
  path: '/specimen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIdRoute = SpeciesIdRouteImport.update({
  id: '/species/$id',
  path: '/species/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBackgroundRoute = ApiRemoveBackgroundRouteImport.update({
  id: '/api/remove-background',
  path: '/api/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/discover': typeof DiscoverRoute
  '/herbarium': typeof HerbariumRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
  '/species/$id': typeof SpeciesIdRoute
  '/specimen/$id': typeof SpecimenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/discover': typeof DiscoverRoute
  '/herbarium': typeof HerbariumRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
  '/species/$id': typeof SpeciesIdRoute
  '/specimen/$id': typeof SpecimenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/discover': typeof DiscoverRoute
  '/herbarium': typeof HerbariumRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
  '/species/$id': typeof SpeciesIdRoute
  '/specimen/$id': typeof SpecimenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/discover'
    | '/herbarium'
    | '/api/remove-background'
    | '/species/$id'
    | '/specimen/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/discover'
    | '/herbarium'
    | '/api/remove-background'
    | '/species/$id'
    | '/specimen/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/discover'
    | '/herbarium'
    | '/api/remove-background'
    | '/species/$id'
    | '/specimen/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  DiscoverRoute: typeof DiscoverRoute
  HerbariumRoute: typeof HerbariumRoute
  ApiRemoveBackgroundRoute: typeof ApiRemoveBackgroundRoute
  SpeciesIdRoute: typeof SpeciesIdRoute
  SpecimenIdRoute: typeof SpecimenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/herbarium': {
      id: '/herbarium'
      path: '/herbarium'
      fullPath: '/herbarium'
      preLoaderRoute: typeof HerbariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specimen/$id': {
      id: '/specimen/$id'
      path: '/specimen/$id'
      fullPath: '/specimen/$id'
      preLoaderRoute: typeof SpecimenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$id': {
      id: '/species/$id'
      path: '/species/$id'
      fullPath: '/species/$id'
      preLoaderRoute: typeof SpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-background': {
      id: '/api/remove-background'
      path: '/api/remove-background'
      fullPath: '/api/remove-background'
      preLoaderRoute: typeof ApiRemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  DiscoverRoute: DiscoverRoute,
  HerbariumRoute: HerbariumRoute,
  ApiRemoveBackgroundRoute: ApiRemoveBackgroundRoute,
  SpeciesIdRoute: SpeciesIdRoute,
  SpecimenIdRoute: SpecimenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
